### PR TITLE
Update owners file

### PR DESCRIPTION
**Pull request by gparvin**
Remove user that no longer needs approval or reviewer access

Refs:
 - https://github.com/stolostron/backlog/issues/21546

Signed-off-by: Gus Parvin <gparvin@redhat.com>

### CODE REVIEW

**Comment by gparvin** [comment]
/hold
Investigating crd issue with new kind node version

**Comment by mprahl** [comment]
@gparvin in the future, that CRD change should be in a separate commit.

**Comment by gparvin** [comment]
Note the CRD change was to get the tests to pass due to kind node images being updated.

**Comment by mprahl** [comment]
> Note the CRD change was to get the tests to pass due to kind node images being updated.

Right, it would still be a separate commit explaining that it was to fix the CI since it's not related to the OWNERS file change.

**Review by mprahl — APPROVED** [review]

**Pull request merged**
