### PR TITLE
Check all items in lists

### PR DESCRIPTION
**Pull request by JustinKuli**
~ACM-7899~ https://issues.redhat.com/browse/ACM-7889

### CODE REVIEW

**Review by dhaiducek — APPROVED** [review]
Approving (while fully knowing I'm going to have to rebase my PR's tests on this code... 🥴 )

**Comment by dhaiducek** [comment]
I'm not sure that's the right Jira issue...

**Comment by JustinKuli** [comment]
Good catch, I meant to write 7889, not 7899

**Review by dhaiducek — APPROVED** [review]
/unhold

**Pull request merged**
