### PR TITLE
Chore: Adding an initial chart package

### PR DESCRIPTION
**Pull request by yue9944882**

### CODE REVIEW

**Comment by dhaiducek** [comment]
Hi, @yue9944882! Thank you for the PR! However, we are developing the GRC Addon Controller to push as a new repo, and these Helm charts will live there. This is also consistent with other components in OCM.

**Comment by dhaiducek** [comment]
Enhancement proposal submitted: 
- https://github.com/open-cluster-management-io/enhancements/pull/44

**Comment by yue9944882** [comment]
@dhaiducek thanks! will move the PR to the new repo then.

**Comment by dhaiducek** [comment]
Closing based on latest comment.

**Pull request closed without merging**
